name: Validate Gradle Wrapper
on: [push, pull_request]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gradle/actions/wrapper-validation@v5